from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from app.auth import verify_api_key
from app.llm_gate import ask_medical_llm
from validator.response_validator import validate_llm_response
from validator.validator_logs import log_validation_attempt

router = APIRouter()


class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="Question generated by the Trad LLM from the patient conversation.",
        examples=["Patient reports sharp chest pain radiating to the left arm for 20 minutes."],
    )


class AskResponse(BaseModel):
    response: str = Field(
        description="Raw response from the medical LLM, passed as-is to the Validator."
    )


@router.post(
    "/ask",
    response_model=AskResponse,
    summary="Send a question to the medical LLM",
    description=(
        "Accepts a question from the Trad LLM, forwards it to the medical LLM "
        "with the clinical system prompt, and returns the raw response for the Validator to parse."
    ),
)
async def ask(
    body: AskRequest,
    _: str = Depends(verify_api_key),
) -> AskResponse:
    try:
        attempt_number = 1

        while attempt_number < 4:
            result = await ask_medical_llm(body.question)

            parsed_result = validate_llm_response(result)

            log_validation_attempt(attempt_number, parsed_result)

            if parsed_result.is_valid:
                return parsed_result.msg

            attempt_number += 1

        print("Failed to parse the llm after 3 attempts")

    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Ollama unreachable or returned an unexpected error: {exc}",
        )

    return AskResponse(response=result)
