from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from app.auth import verify_api_key
from app.llm_gate import ask_medical_llm
from validator.response_validator import validate_llm_response
from validator.validation_logger import log_validation_attempt

router = APIRouter()

MAX_VALIDATION_RETRIES = 3


class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="Question generated by the Trad LLM from the patient conversation.",
        examples=["Patient reports sharp chest pain radiating to the left arm for 20 minutes."],
    )


class AskResponse(BaseModel):
    response: str = Field(
        description="Raw response from the medical LLM, passed as-is to the Validator."
    )


@router.post(
    "/ask",
    response_model=AskResponse,
    summary="Send a question to the medical LLM",
    description=(
        "Accepts a question from the Trad LLM, forwards it to the medical LLM "
        "with the clinical system prompt, and returns the raw response for the Validator to parse."
    ),
)
async def ask(
    body: AskRequest,
    _: str = Depends(verify_api_key),
) -> AskResponse:
    for attempt in range(MAX_VALIDATION_RETRIES):
        try:
            result = await ask_medical_llm(body.question)
        except Exception as error:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=(
                    "Ollama unreachable or returned an unexpected "
                    f"error: {error}"
                ),
            )

        # Validate the response
        validation = validate_llm_response(result)

        # Log the validation attempt
        log_validation_attempt(
            attempt=attempt + 1,
            prompt=body.question,
            validation=validation,
        )

        if validation.is_valid:
            return AskResponse(response=result)

        # If this is the last attempt, return the validation error
        if attempt == MAX_VALIDATION_RETRIES - 1:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=validation.to_error_dict(),
            )

    # Fallback
    raise HTTPException(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        detail="Validation retries exhausted",
    )
